url: https://tosc.in
#baseurl: /agency-jekyll-theme/

# Site settings
title: TeamOSC
email: championswimmer@gmail.com
description: "TeamOSC is a group of Developers from Delhi who build wonderful apps and websites for startups"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Umair Khan
  pic: 1
  position: Founder, The Hacker
  social:
    - title: twitter
      url: #
    - title: facebook
      url: http://fb.me/omerjerk
    - title: stack-overflow
      url: #

- name: Saurav Tomar
  pic: 2
  position: Founder, The Dreamer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Arnav Gupta
  pic: 3
  position: Founder, The Evangelist
  social:
    - title: twitter
      url: http://twitter.com/championswimmer
    - title: facebook
      url: http://fb.me/championswimmer
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/championswimmer
  - title: facebook
    url: http://facebook.com/championswimmer
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket 
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/teamosc

# Postal address (add as many lines as necessary)
address:
  - line: Delhi Technological University
  - line: Shahbad, New Delhi 90210

# Build settings
markdown: kramdown
permalink: pretty